### ISSUE TITLE
Header disappears on third page of table

### ISSUE THREAD

**Issue by kburk1997** [kburk1997/RelieveMe#117]
On the website, under Buildings, the header disappears on the third page.

**Comment by dong-eileen** [comment]
Finished. 
- Turns out that we were just doing the column headings mildly incorrectly.

**Comment by dong-eileen** [comment]
IT'S BACK. But that's okay. Leave it to the person who has to touch it next.

**Comment by dong-eileen** [comment]
Fixed with [commit ](https://github.com/kburk1997/RelieveMe/commit/b99822cdd5886f05c2e0b65de58d129d4df8bc48). Conflicting slot-scopes in the search bar.
