### ISSUE TITLE
Create data structures for backend

### ISSUE THREAD

**Issue by huj13** [kburk1997/RelieveMe#12]
Each schema = 1 domain class
Make sure to make repository for each table.

There is an example already of a BuildingRepository and Building domain class (even if the schema isn't completely accurate)

**Comment by dong-eileen** [comment]
Create a data structure for each schema

**Comment by dong-eileen** [comment]
Expanded upon this. See updated repository, domain, and service packages. Make sure to write tests for Service classes.

Remaining: Floor plan, Bathroom, Floor
