### ISSUE TITLE
Create skeleton feedback page

### ISSUE THREAD

**Issue by kburk1997** [kburk1997/RelieveMe#4]
From UI mockup notes:
When the user enters the page, the category “Feedback” will be automatically selected.
When the user enters their email, the subject line, their feedback, and click submit, they will be directed to a thank you page that states that the email has been sent.
A confirmation email is sent to the user when the submit button is clicked.
When the user submits the form, an email is sent to our team’s inbox with subject line equal to the user-inputted subject, and body of the email equal to the feedback that the user inputted.

**Comment by dong-eileen** [comment]
Finished skeleton with the following features:

- Takes in email, category, subject, and description
- Makes post request to /submit on backend
- Chooses category on page enter based on query parameter
- Redirects user to confirmation page after pressing submit
