### ISSUE TITLE
ComfirmationEmailTest fails

### ISSUE THREAD

**Issue by kburk1997** [kburk1997/RelieveMe#45]
Attached is a screenshot of the terminal when running `mvn clean install`. This fails to run because the ConfirmationEmailTest fails.

![selection_456](https://user-images.githubusercontent.com/11298269/47621315-5c359880-dacc-11e8-8c0f-974f38a13af0.png)

**Comment by kburk1997** [comment]
If this ran successfully on your machines,might just be a linux thing. Temporarily added an extra \n on my local machine until we can work this out at the meeting tomorrow

**Comment by dong-eileen** [comment]
Forgot to close.
