### ISSUE TITLE
Bathroom data - JROWL

### ISSUE THREAD

**Issue by dong-eileen** [kburk1997/RelieveMe#67]
Gather real bathroom data on Jonsson-Rowland Science Center.

Update the [bathroom data spreadsheet](https://docs.google.com/spreadsheets/d/16_L-SjnN7-nsz47uzWSGVcEn8n-CeegjUF_lreaJSrI/edit#gid=1645440414).

Backend:
- Edit data.sql

Insert the following into data.sql:
- In building table:
-- INSERT INTO building (proper_name, region_id) VALUES ('Jonsson-Rowland Science Center', 3);

- In building name table:
-- INSERT INTO building_name (name, building_id) VALUES ('Jonsson-Rowland Science Center', _INSERT NEW BUILDING ID HERE_);
-- INSERT INTO building_name (name, building_id) VALUES ('J-ROWL', _INSERT NEW BUILDING ID HERE_);

- Insert floor data

- Insert floor plan data

- Insert bathroom data

Look at existing data.sql for example queries and format.

**Comment by RachelTheAwesome** [comment]
done.
