### ISSUE TITLE
Top menu

### ISSUE THREAD

**Issue by huj13** [kburk1997/RelieveMe#9]
See the top menu for reference: https://docs.google.com/presentation/d/14ZhnlCIhN5mRDbkYgRWB0Y6PL9r9XBxBU5-hCYgFsuI/edit#slide=id.p

**Comment by dong-eileen** [comment]
See the top menu for reference: https://docs.google.com/presentation/d/14ZhnlCIhN5mRDbkYgRWB0Y6PL9r9XBxBU5-hCYgFsuI/edit#slide=id.p

**Comment by huj13** [comment]
I finished this.
